### PR TITLE
Calling Twilio's Client.account to send SMS.

### PR DESCRIPTION
**Pull request by motro**
According their updated manual: https://www.twilio.com/docs/api/rest/sending-messages

### CODE REVIEW

**Comment by philnash** [comment]
Hey @motro, I'm a developer evangelist for Twilio and I just saw this. You actually don't need to call the `account` method, the `client` implements `method_missing` to pass through any calls the `account` would normally deal with if called on the `client`.

**Comment by motro** [comment]
@philnash, for some reason without this update, Twilio sends my SMS messages in parts (non-english) and with the update those messages get sent just fine, so my guess is that it isn't exactly the same.
Besides, if it's according to your documentation, why not do it?

**Comment by philnash** [comment]
That is weird! Both `client.messages.create` and `client.account.messages.create` should be equivalent. The difference would be if the code was using `client.account.sms.messages.create`. The old SMS/Messages resource, which is deprecated, would split messages up like that.

Which version of the twilio-ruby library do you have installed in your application?

**Comment by motro** [comment]
I'm using 4.11.1

**Comment by philnash** [comment]
That is not expected behaviour. Can you reproduce that outside of the textris gem with just the twilio-ruby gem?

**Comment by m-stachyra** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;hmvr9HjW&#x2F;13-test-trello-s-github-powerup"> Test Trello&#39;s GitHub PowerUp!</a>

**Comment by nowakov** [comment]
Hey @motro what's the status of this PR? Do you need any help with that? Did you manage to reproduce this issue outside of the textris?

**Comment by Lackoftactics** [comment]
As bug can't be reproduced and @philnash said it should work with `client`, I am closing this issue

**Pull request closed without merging**
